=== Kenneth2804/xml-test/products_items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="items">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="item" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:string" />
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="price" type="xs:string" />
                            <xs:element name="stock" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Kenneth2804/xml-test/products_items.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="products_items.xsd">
    <item>
        <id>1</id>
        <name>Producto A</name>
        <price>150</price>
        <stock>20</stock>
    </item>

    <item>
        <id>2</id>
        <name>Producto B</name>
        <price>250</price>
        <stock>10</stock>
    </item>

    <item>
        <id>3</id>
        <name>Producto C</name>
        <price>350</price>
        <stock>5</stock>
    </item>
</items>
